name = "Simplace"
uuid = "b0b0a731-1897-4268-b4ff-e689c85594d9"
authors = ["Gunther Krauss <guntherkrauss@uni-bonn.de>"]
version = "0.0.3"

[deps]
JavaCall = "494afd89-becb-516b-aafa-70d2670c0337"

[compat]
JavaCall = "0.8.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
